data = {
    "january": {
        1: {'expense': '£12.34', 'category': 'bills', 'description': 'January rent'},
        2: {'expense': '£23.45', 'category': 'groceries', 'description': 'Grocery shopping'},
        3: {'expense': '£10.00', 'category': 'petrol', 'description': 'Car fuel'},
        4: {'expense': '£5.60', 'category': 'extra', 'description': 'Coffee'},
        5: {'expense': '£8.99', 'category': 'presents', 'description': 'Gift for friend'},
        6: {'expense': '£15.30', 'category': 'bills', 'description': 'Electricity bill'},
        7: {'expense': '£2.50', 'category': 'groceries', 'description': 'Bread'},
        8: {'expense': '£45.00', 'category': 'petrol', 'description': 'Fuel for the car'},
        9: {'expense': '£9.99', 'category': 'presents', 'description': 'Birthday card'},
        10: {'expense': '£14.75', 'category': 'extra', 'description': 'Lunch out'}
    },
    "february": {
        1: {'expense': '£25.50', 'category': 'bills', 'description': 'February rent'},
        2: {'expense': '£17.80', 'category': 'groceries', 'description': 'Weekly groceries'},
        3: {'expense': '£11.20', 'category': 'petrol', 'description': 'Fuel refill'},
        4: {'expense': '£7.25', 'category': 'extra', 'description': 'Snacks'},
        5: {'expense': '£22.10', 'category': 'presents', 'description': 'Valentine\'s gift'},
        6: {'expense': '£13.40', 'category': 'bills', 'description': 'Water bill'},
        7: {'expense': '£3.00', 'category': 'groceries', 'description': 'Milk'},
        8: {'expense': '£50.00', 'category': 'petrol', 'description': 'Full tank'},
        9: {'expense': '£12.00', 'category': 'presents', 'description': 'Gift wrap'},
        10: {'expense': '£16.50', 'category': 'extra', 'description': 'Dinner out'}
    },
    "march": {
        1: {'expense': '£30.00', 'category': 'bills', 'description': 'March rent'},
        2: {'expense': '£20.00', 'category': 'groceries', 'description': 'Supermarket shopping'},
        3: {'expense': '£12.30', 'category': 'petrol', 'description': 'Gas refill'},
        4: {'expense': '£6.00', 'category': 'extra', 'description': 'Lunch'},
        5: {'expense': '£18.75', 'category': 'presents', 'description': 'Gift for partner'},
        6: {'expense': '£16.80', 'category': 'bills', 'description': 'Internet bill'},
        7: {'expense': '£4.50', 'category': 'groceries', 'description': 'Eggs'},
        8: {'expense': '£55.00', 'category': 'petrol', 'description': 'Tank fill-up'},
        9: {'expense': '£14.99', 'category': 'presents', 'description': 'Special gift'},
        10: {'expense': '£18.00', 'category': 'extra', 'description': 'Takeout'}
    },
    "april": {
        1: {'expense': '£35.00', 'category': 'bills', 'description': 'April rent'},
        2: {'expense': '£22.50', 'category': 'groceries', 'description': 'Weekly shopping'},
        3: {'expense': '£13.40', 'category': 'petrol', 'description': 'Fuel'},
        4: {'expense': '£8.00', 'category': 'extra', 'description': 'Coffee'},
        5: {'expense': '£20.00', 'category': 'presents', 'description': 'Birthday gift'},
        6: {'expense': '£18.50', 'category': 'bills', 'description': 'Gas bill'},
        7: {'expense': '£5.00', 'category': 'groceries', 'description': 'Butter'},
        8: {'expense': '£60.00', 'category': 'petrol', 'description': 'Full tank'},
        9: {'expense': '£15.50', 'category': 'presents', 'description': 'Surprise gift'},
        10: {'expense': '£20.00', 'category': 'extra', 'description': 'Fast food'}
    },
    "may": {
        1: {'expense': '£40.00', 'category': 'bills', 'description': 'May rent'},
        2: {'expense': '£25.00', 'category': 'groceries', 'description': 'Shopping'},
        3: {'expense': '£14.50', 'category': 'petrol', 'description': 'Fuel'},
        4: {'expense': '£9.00', 'category': 'extra', 'description': 'Snack'},
        5: {'expense': '£25.00', 'category': 'presents', 'description': 'Gift for friend'},
        6: {'expense': '£20.00', 'category': 'bills', 'description': 'Electricity'},
        7: {'expense': '£6.00', 'category': 'groceries', 'description': 'Cheese'},
        8: {'expense': '£65.00', 'category': 'petrol', 'description': 'Tank fill'},
        9: {'expense': '£18.00', 'category': 'presents', 'description': 'Anniversary gift'},
        10: {'expense': '£22.00', 'category': 'extra', 'description': 'Dining out'}
    },
    "june": {
        1: {'expense': '£45.00', 'category': 'bills', 'description': 'June rent'},
        2: {'expense': '£30.00', 'category': 'groceries', 'description': 'Weekly groceries'},
        3: {'expense': '£15.00', 'category': 'petrol', 'description': 'Fuel'},
        4: {'expense': '£10.00', 'category': 'extra', 'description': 'Dessert'},
        5: {'expense': '£30.00', 'category': 'presents', 'description': 'Gift for sibling'},
        6: {'expense': '£22.00', 'category': 'bills', 'description': 'Internet'},
        7: {'expense': '£7.00', 'category': 'groceries', 'description': 'Vegetables'},
        8: {'expense': '£70.00', 'category': 'petrol', 'description': 'Full tank'},
        9: {'expense': '£20.00', 'category': 'presents', 'description': 'Surprise gift'},
        10: {'expense': '£25.00', 'category': 'extra', 'description': 'Lunch out'}
    },
    "july": {
        1: {'expense': '£50.00', 'category': 'bills', 'description': 'July rent'},
        2: {'expense': '£32.00', 'category': 'groceries', 'description': 'Grocery shopping'},
        3: {'expense': '£16.00', 'category': 'petrol', 'description': 'Fuel'},
        4: {'expense': '£11.00', 'category': 'extra', 'description': 'Coffee'},
        5: {'expense': '£35.00', 'category': 'presents', 'description': 'Gift for cousin'},
        6: {'expense': '£25.00', 'category': 'bills', 'description': 'Electricity bill'},
        7: {'expense': '£8.00', 'category': 'groceries', 'description': 'Fruit'},
        8: {'expense': '£75.00', 'category': 'petrol', 'description': 'Tank fill'},
        9: {'expense': '£22.00', 'category': 'presents', 'description': 'Gift for niece'},
        10: {'expense': '£30.00', 'category': 'extra', 'description': 'Dinner out'}
    },
    "august": {
        1: {'expense': '£55.00', 'category': 'bills', 'description': 'August rent'},
        2: {'expense': '£35.00', 'category': 'groceries', 'description': 'Monthly groceries'},
        3: {'expense': '£17.00', 'category': 'petrol', 'description': 'Fuel'},
        4: {'expense': '£12.00', 'category': 'extra', 'description': 'Snack'},
        5: {'expense': '£40.00', 'category': 'presents', 'description': 'Gift for parent'},
        6: {'expense': '£28.00', 'category': 'bills', 'description': 'Gas bill'},
        7: {'expense': '£9.00', 'category': 'groceries', 'description': 'Bread'},
        8: {'expense': '£80.00', 'category': 'petrol', 'description': 'Tank full'},
        9: {'expense': '£25.00', 'category': 'presents', 'description': 'Special gift'},
        10: {'expense': '£35.00', 'category': 'extra', 'description': 'Takeaway'}
    },
    "september": {
        1: {'expense': '£60.00', 'category': 'bills', 'description': 'September rent'},
        2: {'expense': '£40.00', 'category': 'groceries', 'description': 'Groceries'},
        3: {'expense': '£18.00', 'category': 'petrol', 'description': 'Fuel'},
        4: {'expense': '£13.00', 'category': 'extra', 'description': 'Coffee'},
        5: {'expense': '£45.00', 'category': 'presents', 'description': 'Gift for friend'},
        6: {'expense': '£30.00', 'category': 'bills', 'description': 'Electricity'},
        7: {'expense': '£10.00', 'category': 'groceries', 'description': 'Vegetables'},
        8: {'expense': '£85.00', 'category': 'petrol', 'description': 'Tank fill'},
        9: {'expense': '£30.00', 'category': 'presents', 'description': 'Birthday gift'},
        10: {'expense': '£40.00', 'category': 'extra', 'description': 'Dinner out'}
    },
    "october": {
        1: {'expense': '£65.00', 'category': 'bills', 'description': 'October rent'},
        2: {'expense': '£45.00', 'category': 'groceries', 'description': 'Monthly groceries'},
        3: {'expense': '£20.00', 'category': 'petrol', 'description': 'Fuel'},
        4: {'expense': '£15.00', 'category': 'extra', 'description': 'Snack'},
        5: {'expense': '£50.00', 'category': 'presents', 'description': 'Gift for sibling'},
        6: {'expense': '£32.00', 'category': 'bills', 'description': 'Internet'},
        7: {'expense': '£11.00', 'category': 'groceries', 'description': 'Fruit'},
        8: {'expense': '£90.00', 'category': 'petrol', 'description': 'Full tank'},
        9: {'expense': '£35.00', 'category': 'presents', 'description': 'Special gift'},
        10: {'expense': '£45.00', 'category': 'extra', 'description': 'Takeaway'}
    },
    "november": {
        1: {'expense': '£70.00', 'category': 'bills', 'description': 'November rent'},
        2: {'expense': '£50.00', 'category': 'groceries', 'description': 'Weekly groceries'},
        3: {'expense': '£22.00', 'category': 'petrol', 'description': 'Fuel'},
        4: {'expense': '£18.00', 'category': 'extra', 'description': 'Coffee'},
        5: {'expense': '£55.00', 'category': 'presents', 'description': 'Gift for partner'},
        6: {'expense': '£35.00', 'category': 'bills', 'description': 'Electricity'},
        7: {'expense': '£12.00', 'category': 'groceries', 'description': 'Cheese'},
        8: {'expense': '£95.00', 'category': 'petrol', 'description': 'Full tank'},
        9: {'expense': '£40.00', 'category': 'presents', 'description': 'Birthday gift'},
        10: {'expense': '£50.00', 'category': 'extra', 'description': 'Dining out'}
    },
    "december": {
        1: {'expense': '£75.00', 'category': 'bills', 'description': 'December rent'},
        2: {'expense': '£55.00', 'category': 'groceries', 'description': 'Holiday groceries'},
        3: {'expense': '£25.00', 'category': 'petrol', 'description': 'Fuel'},
        4: {'expense': '£20.00', 'category': 'extra', 'description': 'Snack'},
        5: {'expense': '£60.00', 'category': 'presents', 'description': 'Christmas gifts'},
        6: {'expense': '£40.00', 'category': 'bills', 'description': 'Internet bill'},
        7: {'expense': '£15.00', 'category': 'groceries', 'description': 'Holiday treats'},
        8: {'expense': '£100.00', 'category': 'petrol', 'description': 'Full tank'},
        9: {'expense': '£50.00', 'category': 'presents', 'description': 'New Year gift'},
        10: {'expense': '£60.00', 'category': 'extra', 'description': 'Dinner out'}
    }
}